### ISSUE TITLE
Fonts are not available

### ISSUE THREAD

**Issue by mjulstein** [Altinn/figma-design-tokens#3]
We need to be able to include the ALTINN-DIN font in the design-system so we can render the components correctly.
@mrosvik Should we export the font through the design-tokens?
Are there any alt-fonts we can use for those who can't access the font?
What about licencing?
WDYT?

The name of the font differs in production: In production the font is called `DIN-reg` etc.
In the design tokens it is exported as `Altinn-DIN` which wont match.
On a side note: I noticed that there are tokens for letter-spacing. I don't believe we have CSS-support for that.

**Comment by haakemon** [comment]
The font-family is available on CDN https://altinncdn.no/fonts/altinn-din/altinn-din.css

It has been included in Storybook in this PR https://github.com/Altinn/altinn-design-system/pull/21 so the previews now should show the correct font-family.

letter-spacing is supported in css as well https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing , although using `%` as a unit (as we currently have in our tokens) is not allowed, so that needs to be changed. cc: @mrosvik

**Comment by mrosvik** [comment]
Ok, so should I just add 3, and you add the % in code?

**Comment by haakemon** [comment]
No, sorry for the confusion. What I meant is that in css, `%` is not a valid unit for letter-spacing. It has to be a [length unit](https://developer.mozilla.org/en-US/docs/Web/CSS/length) , like px, rem, em, or similar. We can still keep the unit in the token.

**Comment by mrosvik** [comment]
Thanks. It is now set to til 0.3px, as we are using in docs. 
<img width="248" alt="image" src="https://user-images.githubusercontent.com/1464915/170119084-43ca8f94-59ae-4c51-a0a3-35f9cf96d597.png">

**Comment by mrosvik** [comment]
Det ser ut til at fonten er her nå https://designsystem.altinn.studio/?path=/story/components-panel--info ? Kan denne issuen lukkes?

**Comment by haakemon** [comment]
Yep, the issue is closed :)
